#!/usr/bin/env python3
"""
ariaska_v5_htb_training.py — Phase 57 HTB-Ready Training Pipeline

Optimized for RTX 5090 / 4080S (32GB VRAM), $10 budget @ $0.12-$0.17/hr.

Track A: LoRA SFT + DPO on ariaska-cybersec2 FP16 → ariaska-cybersec3 (4B)
  Stage 1: LoRA SFT (r=64) — HTB attack chains + schema compliance
  Stage 2: DPO alignment — expert vs novice judgment training
  Stage 3: Merge + GGUF quantize → ready for Ollama

Training data from generate_htb_data.py (93 attack chains, 27 real HTB/THM boxes).
Optional cloud-enhanced reasoning via Groq 70B (--cloud-enhance).

5090 settings: bs=4, grad_accum=4, epochs=3, seq_len=1024 → ~2h SFT + ~1h DPO
4080S settings: bs=2, grad_accum=8, epochs=3, seq_len=1024 → ~4h SFT + ~2h DPO

Usage:
  python ariaska_v5_htb_training.py --all                    # Full pipeline
  python ariaska_v5_htb_training.py --gen-data               # Data only
  python ariaska_v5_htb_training.py --gen-data --cloud-enhance  # Data with Groq 70B
  python ariaska_v5_htb_training.py --track-a                # SFT+DPO+merge
  python ariaska_v5_htb_training.py --gpu 5090               # 5090 batch settings
"""

from __future__ import annotations

import gc
import logging
import os
import subprocess
import sys
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Optional

import torch

_log_handlers: list[logging.Handler] = [logging.StreamHandler(sys.stdout)]
_log_file = Path("/workspace/v5_training.log") if Path("/workspace").exists() else Path("v5_training.log")
try:
    _log_handlers.append(logging.FileHandler(str(_log_file), mode="a"))
except OSError:
    pass  # Skip file logging when path isn't writable (local testing)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=_log_handlers,
)
log = logging.getLogger("ariaska.v5")

# ── Paths ────────────────────────────────────────────────────────────────────

# Track A: 4B LoRA SFT+DPO on existing FP16
CYBERSEC2_FP16 = Path("/workspace/models/ariaska-cybersec2-fp16")
CYBERSEC3_LORA_OUT = Path("/workspace/output/cybersec3-lora")
CYBERSEC3_DPO_OUT = Path("/workspace/output/cybersec3-dpo")
CYBERSEC3_MERGED = Path("/workspace/output/cybersec3-merged")
CYBERSEC3_GGUF = Path("/workspace/output/cybersec3-gguf")

# HuggingFace repos (base model source, output target)
HF_BASE_REPO = "zer0aria/ariaska-cybersec2"

# Data (generated by generate_htb_data.py)
DATA_DIR = Path("/workspace/data")
HTB_SFT_DATA = DATA_DIR / "htb_sft_v5.jsonl"
HTB_DPO_DATA = DATA_DIR / "htb_dpo_v5.jsonl"
SCHEMA_DATA = DATA_DIR / "ariaska_schema_sft_v4.jsonl"

# ── GPU-aware hyperparameters ─────────────────────────────────────────────────

@dataclass(frozen=True)
class GPUConfig:
    """Training hyperparameters tuned for specific GPU."""
    name: str
    sft_batch_size: int
    sft_grad_accum: int
    dpo_batch_size: int
    dpo_grad_accum: int
    num_epochs: int
    dpo_epochs: int

GPU_PRESETS: dict[str, GPUConfig] = {
    "5090": GPUConfig(
        name="RTX 5090 32GB",
        sft_batch_size=4, sft_grad_accum=4,
        dpo_batch_size=2, dpo_grad_accum=8,
        num_epochs=3, dpo_epochs=2,
    ),
    "4080s": GPUConfig(
        name="RTX 4080S 16GB",
        sft_batch_size=2, sft_grad_accum=8,
        dpo_batch_size=1, dpo_grad_accum=16,
        num_epochs=3, dpo_epochs=2,
    ),
}
DEFAULT_GPU = "5090"

ALL_LINEAR = [
    "q_proj", "k_proj", "v_proj", "o_proj",
    "gate_proj", "up_proj", "down_proj",
]


# ═══════════════════════════════════════════════════════════════════════════════
# DATA GENERATION — delegates to generate_htb_data.py
# ═══════════════════════════════════════════════════════════════════════════════


def generate_training_data(
    sft_count: int = 15000,
    dpo_count: int = 2500,
    output_parse_count: int = 2000,
    seed: int = 42,
    cloud_enhance: bool = False,
    cloud_enhance_count: int = 3000,
) -> Dict[str, Path]:
    """Generate all training data via generate_htb_data.py.

    Returns dict mapping data type to output file path.
    """
    DATA_DIR.mkdir(parents=True, exist_ok=True)

    # Locate generator script (same directory as this file)
    gen_script = Path(__file__).parent / "generate_htb_data.py"
    if not gen_script.exists():
        raise FileNotFoundError(f"Generator not found: {gen_script}")

    cmd = [
        sys.executable, str(gen_script),
        "--output-dir", str(DATA_DIR),
        "--sft-count", str(sft_count),
        "--dpo-count", str(dpo_count),
        "--output-parse-count", str(output_parse_count),
        "--seed", str(seed),
    ]
    if cloud_enhance:
        cmd += ["--cloud-enhance", "--cloud-enhance-count", str(cloud_enhance_count)]

    log.info(f"[DATA] Running: {' '.join(cmd)}")
    datagen_log = DATA_DIR / "datagen_progress.log"
    log.info(f"[DATA] Progress log: {datagen_log}")
    with open(datagen_log, "w") as logf:
        result = subprocess.run(cmd, stdout=logf, stderr=subprocess.STDOUT, text=True)
    if result.returncode != 0:
        log.error(f"[DATA] Generator failed — see {datagen_log}")
        # Print last 50 lines for debugging
        try:
            lines = datagen_log.read_text().splitlines()
            log.error(f"[DATA] Last 50 lines:\n" + "\n".join(lines[-50:]))
        except Exception:
            pass
        raise RuntimeError(f"generate_htb_data.py failed (rc={result.returncode})")

    log.info(f"[DATA] Generator complete — see {datagen_log}")

    return {
        "sft": HTB_SFT_DATA,
        "dpo": HTB_DPO_DATA,
    }


def ensure_base_model() -> None:
    """Download base model from HuggingFace if not already present.

    Much faster than SCP from local — vast.ai ↔ HF has datacenter bandwidth.
    """
    config_file = CYBERSEC2_FP16 / "config.json"
    if config_file.exists():
        log.info(f"[BASE] Model already at {CYBERSEC2_FP16}")
        return

    log.info(f"[BASE] Downloading {HF_BASE_REPO}/fp16-merged from HuggingFace...")
    CYBERSEC2_FP16.mkdir(parents=True, exist_ok=True)

    try:
        from huggingface_hub import snapshot_download
        tmp_dir = snapshot_download(
            HF_BASE_REPO,
            allow_patterns=["fp16-merged/*"],
            local_dir=CYBERSEC2_FP16.parent / "_hf_tmp",
            local_dir_use_symlinks=False,
        )
        # Move files from fp16-merged/ subdirectory to the target
        src = Path(tmp_dir) / "fp16-merged"
        if src.exists():
            for f in src.iterdir():
                f.rename(CYBERSEC2_FP16 / f.name)
            (CYBERSEC2_FP16.parent / "_hf_tmp").exists() and None  # cleanup handled by snapshot_download
        log.info(f"[BASE] Downloaded to {CYBERSEC2_FP16}")
    except Exception as e:
        log.error(f"[BASE] HF download failed: {e}")
        log.error("[BASE] Ensure HF_TOKEN is set and has access to the repo")
        raise


# ═══════════════════════════════════════════════════════════════════════════════
# TRACK A: LoRA SFT+DPO on ariaska-cybersec2 → ariaska-cybersec3
# ═══════════════════════════════════════════════════════════════════════════════

def track_a_lora_sft(gpu: GPUConfig) -> None:
    """Stage A1: LoRA SFT on ariaska-cybersec2 FP16 with HTB data."""
    from transformers import AutoModelForCausalLM, AutoTokenizer
    from peft import LoraConfig, get_peft_model
    from trl import SFTTrainer, SFTConfig

    log.info("=" * 70)
    log.info(f"TRACK A — Stage 1: LoRA SFT on ariaska-cybersec2 [{gpu.name}]")
    log.info(f"  bs={gpu.sft_batch_size}, grad_accum={gpu.sft_grad_accum}, epochs={gpu.num_epochs}")
    log.info("=" * 70)

    tokenizer = AutoTokenizer.from_pretrained(str(CYBERSEC2_FP16))
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    model = AutoModelForCausalLM.from_pretrained(
        str(CYBERSEC2_FP16),
        torch_dtype=torch.bfloat16,
        device_map="auto",
        attn_implementation="sdpa",  # flash_attention_2 if available, sdpa fallback
    )

    lora_config = LoraConfig(
        r=64,
        lora_alpha=128,
        target_modules=ALL_LINEAR,
        lora_dropout=0.05,
        bias="none",
        task_type="CAUSAL_LM",
    )
    model = get_peft_model(model, lora_config)
    model.print_trainable_parameters()

    # Merge HTB data with existing schema data (2:1 ratio)
    from datasets import load_dataset, concatenate_datasets

    htb_ds = load_dataset("json", data_files=str(HTB_SFT_DATA), split="train")
    schema_ds = load_dataset("json", data_files=str(SCHEMA_DATA), split="train")
    schema_subset = schema_ds.shuffle(seed=42).select(range(min(1500, len(schema_ds))))
    combined = concatenate_datasets([htb_ds, schema_subset]).shuffle(seed=42)

    log.info(f"[DATA] Combined: {len(htb_ds)} HTB + {len(schema_subset)} schema = {len(combined)}")

    training_args = SFTConfig(
        output_dir=str(CYBERSEC3_LORA_OUT),
        num_train_epochs=gpu.num_epochs,
        per_device_train_batch_size=gpu.sft_batch_size,
        gradient_accumulation_steps=gpu.sft_grad_accum,
        learning_rate=2e-4,
        lr_scheduler_type="cosine",
        warmup_ratio=0.05,
        bf16=True,
        logging_steps=10,
        save_strategy="epoch",
        max_length=1024,
        dataset_text_field=None,  # Uses messages format
        neftune_noise_alpha=5.0,
        report_to="none",
    )

    trainer = SFTTrainer(
        model=model,
        args=training_args,
        train_dataset=combined,
        processing_class=tokenizer,
    )

    log.info("[TRAIN] Starting LoRA SFT...")
    trainer.train()
    trainer.save_model(str(CYBERSEC3_LORA_OUT))
    tokenizer.save_pretrained(str(CYBERSEC3_LORA_OUT))
    log.info(f"[DONE] LoRA SFT saved → {CYBERSEC3_LORA_OUT}")

    del model, trainer
    gc.collect()
    torch.cuda.empty_cache()


def track_a_dpo(gpu: GPUConfig) -> None:
    """Stage A2: DPO alignment on SFT checkpoint using expert vs novice pairs."""
    from transformers import AutoModelForCausalLM, AutoTokenizer
    from peft import LoraConfig
    from trl import DPOConfig, DPOTrainer

    log.info("=" * 70)
    log.info(f"TRACK A — Stage 2: DPO Alignment [{gpu.name}]")
    log.info(f"  bs={gpu.dpo_batch_size}, grad_accum={gpu.dpo_grad_accum}, epochs={gpu.dpo_epochs}")
    log.info("=" * 70)

    if not HTB_DPO_DATA.exists():
        log.warning(f"[SKIP] DPO data not found at {HTB_DPO_DATA} — skipping DPO stage")
        return

    from datasets import load_dataset
    dpo_ds = load_dataset("json", data_files=str(HTB_DPO_DATA), split="train")
    if len(dpo_ds) < 50:
        log.warning(f"[SKIP] Only {len(dpo_ds)} DPO examples — need at least 50, skipping")
        return

    log.info(f"[DATA] DPO dataset: {len(dpo_ds)} preference pairs")

    tokenizer = AutoTokenizer.from_pretrained(str(CYBERSEC3_LORA_OUT))
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    model = AutoModelForCausalLM.from_pretrained(
        str(CYBERSEC3_LORA_OUT),
        torch_dtype=torch.bfloat16,
        device_map="auto",
        attn_implementation="sdpa",  # flash_attention_2 if available, sdpa fallback
    )

    # Lighter LoRA for DPO — smaller rank to avoid catastrophic forgetting
    lora_config = LoraConfig(
        r=32,
        lora_alpha=64,
        target_modules=ALL_LINEAR,
        lora_dropout=0.05,
        bias="none",
        task_type="CAUSAL_LM",
    )

    dpo_config = DPOConfig(
        output_dir=str(CYBERSEC3_DPO_OUT),
        num_train_epochs=gpu.dpo_epochs,
        per_device_train_batch_size=gpu.dpo_batch_size,
        gradient_accumulation_steps=gpu.dpo_grad_accum,
        learning_rate=5e-5,
        lr_scheduler_type="cosine",
        warmup_ratio=0.1,
        bf16=True,
        logging_steps=10,
        save_strategy="epoch",
        max_length=1024,
        beta=0.1,  # KL penalty — lower = more aggressive preference learning
        report_to="none",
    )

    trainer = DPOTrainer(
        model=model,
        args=dpo_config,
        train_dataset=dpo_ds,
        processing_class=tokenizer,
        peft_config=lora_config,
    )

    log.info("[TRAIN] Starting DPO alignment...")
    trainer.train()
    trainer.save_model(str(CYBERSEC3_DPO_OUT))
    tokenizer.save_pretrained(str(CYBERSEC3_DPO_OUT))
    log.info(f"[DONE] DPO model saved → {CYBERSEC3_DPO_OUT}")

    del model, trainer
    gc.collect()
    torch.cuda.empty_cache()


def track_a_merge_gguf() -> None:
    """Stage A3: Merge LoRA + quantize to GGUF.

    Picks the best checkpoint: DPO output if available, else SFT output.
    """
    from peft import AutoPeftModelForCausalLM
    from transformers import AutoTokenizer

    log.info("=" * 70)
    log.info("TRACK A — Stage 3: Merge LoRA → GGUF")
    log.info("=" * 70)

    # Use DPO checkpoint if it exists, otherwise fall back to SFT
    checkpoint_dir = CYBERSEC3_DPO_OUT if CYBERSEC3_DPO_OUT.exists() else CYBERSEC3_LORA_OUT
    log.info(f"[MERGE] Loading from: {checkpoint_dir}")

    model = AutoPeftModelForCausalLM.from_pretrained(
        str(checkpoint_dir),
        torch_dtype=torch.bfloat16,
        device_map="cpu",
    )
    merged = model.merge_and_unload()

    CYBERSEC3_MERGED.mkdir(parents=True, exist_ok=True)
    merged.save_pretrained(str(CYBERSEC3_MERGED))

    tokenizer = AutoTokenizer.from_pretrained(str(checkpoint_dir))
    tokenizer.save_pretrained(str(CYBERSEC3_MERGED))

    log.info(f"[MERGED] FP16 model → {CYBERSEC3_MERGED}")

    # Convert to GGUF
    CYBERSEC3_GGUF.mkdir(parents=True, exist_ok=True)

    for quant in ["Q8_0"]:
        out_file = CYBERSEC3_GGUF / f"ariaska-cybersec3-{quant.lower()}.gguf"
        cmd = [
            "python", "-m", "llama_cpp.convert",
            "--outfile", str(out_file),
            "--outtype", quant.lower().replace("_", "-"),
            str(CYBERSEC3_MERGED),
        ]
        log.info(f"[GGUF] Converting {quant}...")
        try:
            subprocess.run(cmd, check=True, capture_output=True)
            log.info(f"[GGUF] {quant} → {out_file}")
        except (subprocess.CalledProcessError, FileNotFoundError):
            # Fallback: try llama.cpp convert directly
            log.warning(f"[GGUF] llama_cpp.convert failed, trying llama-quantize...")
            try:
                # First convert to f16 gguf
                f16_gguf = CYBERSEC3_GGUF / "ariaska-cybersec3-f16.gguf"
                subprocess.run(
                    ["python", "/workspace/llama.cpp/convert_hf_to_gguf.py",
                     str(CYBERSEC3_MERGED), "--outfile", str(f16_gguf), "--outtype", "f16"],
                    check=True,
                )
                subprocess.run(
                    ["/workspace/llama.cpp/build/bin/llama-quantize",
                     str(f16_gguf), str(out_file), quant],
                    check=True,
                )
                log.info(f"[GGUF] {quant} → {out_file}")
            except Exception as e:
                log.error(f"[GGUF] Failed {quant}: {e}")

    del model, merged
    gc.collect()


def upload_to_huggingface(
    repo_id: str = "zer0aria/ariaska-cybersec3",
    upload_fp16: bool = True,
    upload_gguf: bool = True,
) -> None:
    """Upload merged FP16 and/or GGUF models to HuggingFace Hub.

    Much faster than scp from vast.ai — HF has high-bandwidth ingress.
    Download locally via: huggingface-cli download zer0aria/ariaska-cybersec3
    """
    log.info("=" * 70)
    log.info(f"UPLOADING TO HUGGINGFACE: {repo_id}")
    log.info("=" * 70)

    try:
        from huggingface_hub import HfApi, create_repo
    except ImportError:
        log.info("[HF] Installing huggingface_hub...")
        subprocess.run([sys.executable, "-m", "pip", "install", "huggingface_hub"], check=True)
        from huggingface_hub import HfApi, create_repo

    api = HfApi()

    # Create repo if it doesn't exist
    try:
        create_repo(repo_id, repo_type="model", exist_ok=True, private=True)
        log.info(f"[HF] Repository {repo_id} ready")
    except Exception as e:
        log.warning(f"[HF] Repo creation note: {e}")

    if upload_fp16 and CYBERSEC3_MERGED.exists():
        log.info(f"[HF] Uploading FP16 model from {CYBERSEC3_MERGED}...")
        api.upload_folder(
            folder_path=str(CYBERSEC3_MERGED),
            repo_id=repo_id,
            path_in_repo="fp16",
            commit_message="ariaska-cybersec3 FP16 merged model",
        )
        log.info("[HF] FP16 upload complete")

    if upload_gguf and CYBERSEC3_GGUF.exists():
        log.info(f"[HF] Uploading GGUF files from {CYBERSEC3_GGUF}...")
        api.upload_folder(
            folder_path=str(CYBERSEC3_GGUF),
            repo_id=repo_id,
            path_in_repo="gguf",
            commit_message="ariaska-cybersec3 GGUF quantizations",
        )
        log.info("[HF] GGUF upload complete")

    log.info(f"[HF] Done — download with: huggingface-cli download {repo_id}")


# ═══════════════════════════════════════════════════════════════════════════════
# MAIN ENTRY POINT
# ═══════════════════════════════════════════════════════════════════════════════

def main() -> None:
    import argparse

    parser = argparse.ArgumentParser(description="Ariaska V5 HTB Training Pipeline")
    parser.add_argument("--all", action="store_true", help="Full pipeline: gen-data → SFT → DPO → merge → GGUF → HF upload")
    parser.add_argument("--track-a", action="store_true", help="Train only: SFT → DPO → merge → GGUF")
    parser.add_argument("--gen-data", action="store_true", help="Generate training data only")
    parser.add_argument("--gpu", choices=list(GPU_PRESETS.keys()), default=DEFAULT_GPU,
                        help=f"GPU preset for batch sizes (default: {DEFAULT_GPU})")
    parser.add_argument("--sft-count", type=int, default=15000, help="Number of SFT examples")
    parser.add_argument("--dpo-count", type=int, default=2500, help="Number of DPO pairs")
    parser.add_argument("--cloud-enhance", action="store_true",
                        help="Use Groq/OpenRouter/Together 70B for expert reasoning (KD)")
    parser.add_argument("--cloud-enhance-count", type=int, default=10000,
                        help="Max examples to enhance with cloud LLM (default: 10000 = nearly all)")
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--skip-dpo", action="store_true", help="Skip DPO stage (SFT only)")
    parser.add_argument("--hf-upload", action="store_true",
                        help="Upload FP16 + GGUF to HuggingFace after training")
    parser.add_argument("--hf-repo", default="zer0aria/ariaska-cybersec3",
                        help="HuggingFace repo ID for upload")
    args = parser.parse_args()

    gpu = GPU_PRESETS[args.gpu]
    start = time.time()

    log.info("=" * 70)
    log.info(f"Ariaska V5 Training Pipeline — {gpu.name}")
    log.info(f"  GPU preset: {args.gpu} | SFT bs={gpu.sft_batch_size}×{gpu.sft_grad_accum}")
    log.info(f"  DPO bs={gpu.dpo_batch_size}×{gpu.dpo_grad_accum} | Epochs: SFT={gpu.num_epochs} DPO={gpu.dpo_epochs}")
    if args.cloud_enhance:
        log.info(f"  Cloud KD: enhancing up to {args.cloud_enhance_count} examples with 70B teacher")
    log.info("=" * 70)

    # ── Stage 0: Generate training data ──────────────────────────────────────
    if args.gen_data or args.all:
        log.info("=" * 70)
        log.info("STAGE 0: GENERATING TRAINING DATA")
        log.info("=" * 70)
        generate_training_data(
            sft_count=args.sft_count,
            dpo_count=args.dpo_count,
            seed=args.seed,
            cloud_enhance=args.cloud_enhance,
            cloud_enhance_count=args.cloud_enhance_count,
        )

    if args.gen_data:
        log.info(f"[DONE] Data generation complete in {time.time() - start:.0f}s")
        return

    # ── Stage 1–3: Train + merge ─────────────────────────────────────────────
    if args.track_a or args.all:
        ensure_base_model()  # Pull from HF if not already on disk
        track_a_lora_sft(gpu)

        if not args.skip_dpo:
            track_a_dpo(gpu)

        track_a_merge_gguf()

    # ── Stage 4: Upload to HuggingFace ───────────────────────────────────────
    if args.hf_upload or args.all:
        upload_to_huggingface(repo_id=args.hf_repo)

    elapsed = time.time() - start
    log.info("=" * 70)
    log.info(f"ALL DONE — {elapsed / 3600:.1f} hours total")
    log.info("=" * 70)
    log.info("Next steps:")
    log.info(f"  1. Download from HuggingFace:")
    log.info(f"       huggingface-cli download {args.hf_repo} --local-dir ~/models/ariaska-cybersec3")
    log.info("  2. Create Modelfile and register in Ollama:")
    log.info("       ollama create ariaska-cybersec3 -f Modelfile_ariaska_cybersec3")
    log.info("  3. Update ARIASKA_FAST_MODEL and ARIASKA_MEDIUM_MODEL env vars")
    log.info("  4. Run RL retraining: python scripts/offline_distill.py")


if __name__ == "__main__":
    main()
