#!/usr/bin/env python3
"""
train_schema_sft.py - Schema SFT Training for Ariaska 4B Model

QLoRA fine-tuning on schema-perfect synthetic data generated by Qwen3-32B teacher.
Trains Qwen3.5-4B to produce perfect Ariaska JSON schemas.
"""

import json
import os
import sys
import argparse
from pathlib import Path

import torch
from datasets import Dataset
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    TrainingArguments,
)
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training, TaskType
from trl import SFTTrainer, SFTConfig


def load_dataset_from_jsonl(path: str) -> Dataset:
    """Load JSONL dataset with chat messages."""
    examples = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            ex = json.loads(line)
            if "messages" in ex:
                examples.append(ex)
    
    print(f"Loaded {len(examples)} examples from {path}")
    
    # Verify schema distribution
    from collections import Counter
    dist = Counter(ex.get("schema_type", "unknown") for ex in examples)
    print("Schema distribution:")
    for k, v in sorted(dist.items()):
        print(f"  {k}: {v}")
    
    return Dataset.from_list(examples)


def main():
    parser = argparse.ArgumentParser(description="Schema SFT Training")
    parser.add_argument("--data", default="/workspace/data/ariaska_schema_sft.jsonl")
    parser.add_argument("--base-model", default="/workspace/models/qwen3.5-4b")
    parser.add_argument("--output", default="/workspace/models/ariaska-schema-sft")
    parser.add_argument("--epochs", type=int, default=3)
    parser.add_argument("--lr", type=float, default=2e-5)
    parser.add_argument("--batch-size", type=int, default=4)
    parser.add_argument("--grad-accum", type=int, default=4)
    parser.add_argument("--max-seq-len", type=int, default=2048)
    parser.add_argument("--lora-r", type=int, default=32)
    parser.add_argument("--lora-alpha", type=int, default=64)
    parser.add_argument("--lora-dropout", type=float, default=0.05)
    parser.add_argument("--resume", action="store_true", help="Resume from checkpoint")
    args = parser.parse_args()
    
    print(f"=== Ariaska Schema SFT Training ===")
    print(f"Base model: {args.base_model}")
    print(f"Data: {args.data}")
    print(f"Output: {args.output}")
    print(f"Epochs: {args.epochs}, LR: {args.lr}")
    print(f"LoRA r={args.lora_r} alpha={args.lora_alpha}")
    
    # 1. Load tokenizer
    print("\n[1/5] Loading tokenizer...")
    tokenizer = AutoTokenizer.from_pretrained(
        args.base_model,
        trust_remote_code=True,
        padding_side="right",
    )
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token
    
    # 2. Load model with 4-bit quantization
    print("[2/5] Loading model with QLoRA quantization...")
    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.bfloat16,
        bnb_4bit_use_double_quant=True,
    )
    
    model = AutoModelForCausalLM.from_pretrained(
        args.base_model,
        quantization_config=bnb_config,
        device_map="auto",
        trust_remote_code=True,
        torch_dtype=torch.bfloat16,
        attn_implementation="sdpa",  # flash_attention_2 crashes on Qwen3.5 hybrid attention
    )
    model = prepare_model_for_kbit_training(model)
    
    # 3. Configure LoRA
    print("[3/5] Configuring LoRA adapters...")
    lora_config = LoraConfig(
        task_type=TaskType.CAUSAL_LM,
        r=args.lora_r,
        lora_alpha=args.lora_alpha,
        lora_dropout=args.lora_dropout,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                        "gate_proj", "up_proj", "down_proj"],
        bias="none",
    )
    model = get_peft_model(model, lora_config)
    model.print_trainable_parameters()
    
    # 4. Load dataset
    print("[4/5] Loading dataset...")
    dataset = load_dataset_from_jsonl(args.data)
    
    # Split: 95% train, 5% eval
    split = dataset.train_test_split(test_size=0.05, seed=42)
    train_dataset = split["train"]
    eval_dataset = split["test"]
    print(f"Train: {len(train_dataset)}, Eval: {len(eval_dataset)}")
    
    # 5. Configure training
    print("[5/5] Starting training...")
    
    output_dir = args.output
    
    training_args = SFTConfig(
        output_dir=output_dir,
        num_train_epochs=args.epochs,
        per_device_train_batch_size=args.batch_size,
        per_device_eval_batch_size=args.batch_size,
        gradient_accumulation_steps=args.grad_accum,
        learning_rate=args.lr,
        lr_scheduler_type="cosine",
        warmup_ratio=0.05,
        weight_decay=0.01,
        max_grad_norm=1.0,
        logging_steps=10,
        eval_strategy="steps",
        eval_steps=200,
        save_strategy="steps",
        save_steps=500,
        save_total_limit=3,
        fp16=False,
        bf16=True,
        gradient_checkpointing=True,
        gradient_checkpointing_kwargs={"use_reentrant": False},
        optim="paged_adamw_8bit",
        neftune_noise_alpha=5.0,  # NEFTune: +5-10% quality, zero cost
        report_to="none",
        max_seq_length=args.max_seq_len,
        dataset_text_field=None,  # Using chat template
        packing=False,
    )
    
    # Format function to apply chat template
    def formatting_func(examples):
        texts = []
        for msgs in examples["messages"]:
            text = tokenizer.apply_chat_template(
                msgs, tokenize=False, add_generation_prompt=False
            )
            texts.append(text)
        return texts
    
    trainer = SFTTrainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=eval_dataset,
        processing_class=tokenizer,
        formatting_func=formatting_func,
    )
    
    # Resume from checkpoint if specified
    if args.resume and Path(output_dir).exists():
        checkpoints = sorted(Path(output_dir).glob("checkpoint-*"))
        if checkpoints:
            resume_ckpt = str(checkpoints[-1])
            print(f"Resuming from {resume_ckpt}")
            trainer.train(resume_from_checkpoint=resume_ckpt)
        else:
            trainer.train()
    else:
        trainer.train()
    
    # Save final adapter to output/final/ (pipeline expects this path)
    final_dir = str(Path(output_dir) / "final")
    Path(final_dir).mkdir(parents=True, exist_ok=True)
    print(f"\nSaving final adapter to {final_dir}...")
    trainer.save_model(final_dir)
    tokenizer.save_pretrained(final_dir)
    
    # Evaluate
    metrics = trainer.evaluate()
    print(f"Final eval metrics: {json.dumps(metrics, indent=2)}")
    with open(str(Path(output_dir) / "sft_metrics.json"), "w") as f:
        json.dump(metrics, f, indent=2)
    
    print(f"\n=== SFT TRAINING COMPLETE ===")
    print(f"LoRA adapter: {final_dir}")


if __name__ == "__main__":
    main()
