"""
Command Enrichment — Populate assigned_agents, not_when, follows_after, enables
for ALL 224+ registered CommandTemplates.

Called once on import to enrich the registry with full tactical metadata.
This keeps the main registry file clean while adding deep pentesting knowledge.

Author: Phase 9.3
"""

from typing import Dict, List, Set, Any


# =============================================================================
# AGENT ASSIGNMENT MAP
# =============================================================================
# Maps command names → list of agents that should use them.
# Agents: "red" (offensive), "scout" (recon), "blue" (defense),
#         "shadow" (stealth), "orion" (strategic)

AGENT_MAP: Dict[str, List[str]] = {
    # --- RECON ---
    "nmap_quick_scan": ["scout"],
    "nmap_top_ports": ["scout"],
    "nmap_full_tcp": ["scout"],
    "nmap_service_version": ["scout"],
    "nmap_vuln_scan": ["scout", "red"],
    "nmap_udp_scan": ["scout"],
    "masscan_fast": ["scout"],
    "nmap_os_detection": ["scout"],
    "whatweb": ["scout"],
    "curl_headers": ["scout"],
    "nmap_stealth_scan": ["scout", "shadow"],
    "nmap_comprehensive": ["scout"],
    "dns_enum": ["scout"],
    "whois_lookup": ["scout"],
    "nmap_port_21": ["scout"],
    "nmap_port_6667": ["scout"],
    "nmap_port_1524": ["scout"],
    "nmap_port_8180": ["scout"],
    "nmap_port_5432": ["scout"],
    "nmap_rservices": ["scout"],
    "rpcinfo_check": ["scout"],

    # --- ENUMERATION ---
    "gobuster_dir": ["scout", "red"],
    "gobuster_vhost": ["scout"],
    "ffuf_fuzz": ["scout", "red"],
    "nikto_scan": ["scout"],
    "wfuzz_params": ["scout", "red"],
    "feroxbuster": ["scout"],
    "smbclient_list": ["scout"],
    "smbclient_connect": ["scout", "red"],
    "smbclient_auth": ["red"],
    "smbmap_shares": ["scout"],
    "enum4linux_full": ["scout"],
    "enum4linux_ng": ["scout"],
    "ldapsearch_base": ["scout"],
    "ldapsearch_users": ["scout"],
    "windapsearch": ["scout"],
    "dig_any": ["scout"],
    "dig_axfr": ["scout"],
    "dnsrecon": ["scout"],
    "ssh_audit": ["scout"],
    "snmpwalk": ["scout"],
    "onesixtyone": ["scout"],
    "showmount": ["scout"],
    "rpcclient_null": ["scout"],
    "rpcclient_enumdomusers": ["scout"],
    "ftp_anonymous": ["scout", "red"],
    "hydra_ssh": ["red"],
    "hydra_ftp": ["red"],
    "hydra_http_form": ["red"],
    "cme_ldap_users": ["scout"],
    "cme_smb_shares": ["scout"],
    "impacket_reg": ["red"],
    "wpscan": ["scout"],
    "nuclei_scan": ["scout"],
    "dirsearch": ["scout"],
    "cme_smb_bruteforce": ["red"],
    "sqlmap_test": ["red"],
    "searchsploit": ["scout", "red"],
    "redis_cli": ["red"],
    "certipy_find": ["scout", "red"],
    "enum4linux_scan": ["scout"],
    "showmount_enum": ["scout"],
    "tomcat_cred_test": ["red"],
    "psql_default_creds": ["red"],
    "joomscan": ["scout"],
    "droopescan": ["scout"],

    # --- EXPLOITATION ---
    "nfs_mount": ["red"],
    "hydra_smb": ["red"],
    "crackmapexec_smb_bruteforce": ["red"],
    "crackmapexec_winrm": ["red"],
    "impacket_psexec": ["red"],
    "impacket_wmiexec": ["red"],
    "impacket_smbexec": ["red"],
    "impacket_GetNPUsers": ["red"],
    "impacket_GetUserSPNs": ["red"],
    "sqlmap_get": ["red"],
    "sqlmap_post": ["red"],
    "sqlmap_shell": ["red"],
    "evil_winrm": ["red"],
    "evil_winrm_hash": ["red"],
    "ssh_login": ["red"],
    "ssh_key_login": ["red"],
    "knock": ["red", "shadow"],
    "nmap_port_knock": ["red", "shadow"],
    "cme_exec_command": ["red"],
    "msfconsole_exploit": ["red"],
    "msfvenom_payload": ["red"],
    "impacket_atexec": ["red"],
    "impacket_dcomexec": ["red"],
    "msfconsole_auto": ["red"],
    "mysql_login": ["red"],
    "mssql_login": ["red"],
    "rubeus_asreproast": ["red"],
    "rubeus_kerberoast": ["red"],
    "vsftpd_exploit": ["red"],
    "unrealircd_exploit": ["red"],
    "telnet_1524": ["red"],
    "root_shell_confirm": ["red"],
    "rsh_root": ["red"],
    "rlogin_root": ["red"],
    "war_deploy": ["red"],
    "psql_rce": ["red"],
    # --- Phase 18: Direct Exploit Scripts ---
    "vsftpd_backdoor_nc": ["red"],
    "vsftpd_backdoor_python": ["red"],
    "unrealircd_backdoor_nc": ["red"],
    "ingreslock_shell": ["red"],
    "samba_usermap_exploit": ["red"],
    "tomcat_war_deploy": ["red"],
    "mysql_noauth_root": ["red"],
    "postgres_default_rce": ["red"],
    "rlogin_noauth": ["red"],
    "vnc_password_connect": ["red"],
    "nfs_mount_root": ["red"],
    "python_reverse_shell": ["red"],
    "tty_stabilize": ["red"],
    # --- Phase 19: HTB Soulmate / CrushFTP / Erlang / PCAP ---
    "crushftp_auth_bypass": ["red"],
    "crushftp_admin_reset_password": ["red"],
    "crushftp_ftp_upload_shell": ["red"],
    "crushftp_ssh_as_user": ["red"],
    "erlang_cookie_extract": ["red"],
    "erlang_otp_rce": ["red"],
    "pcap_download_extract": ["red", "scout"],
    "tshark_pcap_creds": ["red", "scout"],
    "vhost_discover": ["scout", "red"],
    "ssti_detect_jinja2": ["red", "scout"],
    "ssti_exploit_jinja2": ["red"],
    "ssti_detect_twig": ["red", "scout"],
    "ssti_exploit_twig": ["red"],
    "ssti_detect_erb": ["red", "scout"],
    "tplmap_scan": ["red", "scout"],
    "lfi_etc_passwd": ["red"],
    "lfi_double_encode": ["red"],
    "lfi_php_filter": ["red"],
    "lfi_log_poison": ["red"],
    "lfi_ssh_key": ["red"],
    "rfi_php_shell": ["red"],
    "ssrf_localhost_scan": ["red"],
    "ssrf_cloud_metadata": ["red"],
    "ssrf_internal_admin": ["red"],
    "cmd_inject_semicolon": ["red"],
    "cmd_inject_pipe": ["red"],
    "cmd_inject_backtick": ["red"],
    "cmd_inject_blind_sleep": ["red"],
    "shellshock_cgi": ["red"],
    "heartbleed_exploit": ["red"],
    "log4shell_detect": ["red", "scout"],
    "drupalgeddon2": ["red"],
    "upload_php_double_ext": ["red"],
    "upload_php_magic_bytes": ["red"],
    "upload_htaccess": ["red"],
    "upload_aspx_shell": ["red"],
    "webshell_cmd": ["red"],
    "ysoserial_java": ["red"],
    "phpggc_laravel": ["red"],
    "jwt_none_attack": ["red"],
    "jwt_crack_secret": ["red"],
    "xxe_file_read": ["red"],
    "nosqli_login_bypass": ["red"],
    "revshell_bash": ["red"],
    "revshell_python": ["red"],
    "revshell_powershell": ["red"],
    "crackmapexec_password_spray": ["red"],

    # --- PRIVILEGE ESCALATION ---
    "linpeas": ["red"],
    "linpeas_local": ["red"],
    "sudo_list": ["red"],
    "find_suid": ["red"],
    "find_capabilities": ["red"],
    "find_writable_etc": ["red"],
    "pspy": ["red"],
    "kernel_exploit_check": ["red"],
    "winpeas": ["red"],
    "whoami_all": ["red"],
    "systeminfo": ["red"],
    "windows_exploit_suggester": ["red"],
    "accesschk_services": ["red"],
    "powerup": ["red"],
    "sudo_check": ["red"],
    "certipy_req": ["red"],
    "find_sgid": ["red"],
    "cron_check": ["red"],
    "writable_etc_passwd": ["red"],
    "capability_check": ["red"],
    "docker_privesc": ["red"],
    "lxd_privesc": ["red"],
    "pspy_monitor": ["red"],
    "ssh_key_plant": ["red"],
    "docker_sock_escape": ["red"],
    "lxd_escape": ["red"],

    # --- LATERAL MOVEMENT ---
    "bloodhound_python": ["red", "scout"],
    "sharphound": ["red"],
    "impacket_pth_psexec": ["red"],
    "crackmapexec_pth": ["red"],
    "responder": ["red"],
    "ntlmrelayx": ["red"],
    "chisel_server": ["red"],
    "chisel_client": ["red"],
    "ligolo_agent": ["red"],
    "ssh_tunnel_local": ["red"],
    "ssh_tunnel_dynamic": ["red"],
    "pivot_scan": ["red", "scout"],
    "nmap_pivot": ["scout"],
    "proxychains_scan": ["scout"],
    "winrm_exec": ["red"],
    "ssh_lateral": ["red"],

    # --- EXFILTRATION ---
    "nc_exfil": ["red"],
    "curl_exfil": ["red"],
    "scp_exfil": ["red"],
    "exfil_data": ["red"],
    "dns_exfil": ["red", "shadow"],
    "icmp_exfil": ["red", "shadow"],
    "base64_exfil": ["red"],
    "smb_exfil": ["red"],
    "exfil_shadow": ["red"],
    "exfil_ssh_keys": ["red"],
    "exfil_mysql_dump": ["red"],

    # --- POST EXPLOITATION ---
    "impacket_secretsdump": ["red"],
    "secretsdump_dc": ["red"],
    "mimikatz_logonpasswords": ["red"],
    "mimikatz_sam": ["red"],
    "mimikatz_dcsync": ["red"],
    "cron_backdoor": ["red"],
    "ssh_key_persistence": ["red"],
    "credential_dump": ["red"],
    "hashdump": ["red"],
    "keylogger_deploy": ["red"],
    "history_dump": ["red"],
    "network_config_dump": ["red", "scout"],
    "ssh_key_harvest": ["red"],
    "cleanup_logs": ["red", "shadow"],
    "timestomp": ["red", "shadow"],
    "dump_shadow": ["red"],
    "dump_passwd": ["red"],
    "plant_ssh_key": ["red"],

    # --- CLOSEOUT ---
    "remove_uploaded_tools": ["red", "blue"],
    "remove_ssh_keys_planted": ["red", "blue"],
    "remove_cron_backdoors": ["red", "blue"],
    "verify_target_stable": ["blue", "orion"],
    "cleanup_tmp_artifacts": ["red", "blue"],
    "clear_bash_history": ["red", "shadow"],
    "clear_auth_logs": ["red", "shadow"],
    "clear_wtmp_btmp": ["red", "shadow"],
    "shred_sensitive_files": ["red", "shadow"],
    "timestomp_closeout": ["red", "shadow"],
    "clear_syslog": ["red", "shadow"],
    "remove_known_hosts": ["red", "shadow"],
    "generate_report": ["orion"],
}


# =============================================================================
# NOT_WHEN MAP — Contraindications for each command
# =============================================================================

NOT_WHEN_MAP: Dict[str, str] = {
    # RECON
    "nmap_quick_scan": "Already have host list; target IPs confirmed alive",
    "nmap_top_ports": "Already ran full TCP scan; all ports already known",
    "nmap_full_tcp": "Time-critical engagement; top-ports scan already sufficient for exploitation",
    "nmap_service_version": "Stealth is paramount — version probes generate identifiable traffic",
    "nmap_vuln_scan": "Stealth required — vuln scripts are noisy and easily detected by IDS",
    "nmap_udp_scan": "Time-limited engagement — UDP scans are extremely slow",
    "masscan_fast": "Stealth required — masscan generates massive traffic spikes",
    "nmap_os_detection": "Already identified OS through service banners; IDS alert level is high",
    "whatweb": "No HTTP service detected on target",
    "curl_headers": "No HTTP service detected on target",
    "nmap_stealth_scan": "Already have complete port list from prior scan",
    "nmap_comprehensive": "Time-limited engagement — this scan takes very long",
    "dns_enum": "Target is an IP-only scope with no associated domain",
    "whois_lookup": "Internal network target — whois only works for public domains",
    "nmap_port_21": "Port 21 already confirmed open/closed",
    "nmap_port_6667": "Port 6667 already confirmed open/closed",
    "nmap_port_1524": "Port 1524 already confirmed open/closed",
    "nmap_port_8180": "Port 8180 already confirmed open/closed",
    "nmap_port_5432": "Port 5432 already confirmed open/closed",
    "nmap_rservices": "Ports 512-514 already confirmed; target is modern Linux (no rservices)",
    "rpcinfo_check": "No RPC service detected (port 111 closed)",

    # ENUMERATION
    "gobuster_dir": "No web server detected; or already have comprehensive directory list",
    "gobuster_vhost": "No web server; or not expecting virtual hosts (IP-only target)",
    "ffuf_fuzz": "No web application identified; no fuzzing vectors found",
    "nikto_scan": "Stealth required — nikto is very noisy and easily detected",
    "wfuzz_params": "No web application parameters identified for fuzzing",
    "feroxbuster": "Already have comprehensive directory enumeration results",
    "smbclient_list": "No SMB service (445/139) detected on target",
    "smbclient_connect": "No SMB shares discovered; or no accessible shares found",
    "smbclient_auth": "No credentials available; anonymous access sufficient",
    "smbmap_shares": "No SMB service detected; already have share permissions map",
    "enum4linux_full": "No SMB/RPC service; target is not Windows/Samba",
    "enum4linux_ng": "No SMB/RPC service; already ran enum4linux_full",
    "ldapsearch_base": "No LDAP service (port 389/636) detected",
    "ldapsearch_users": "No LDAP service; not a domain controller",
    "windapsearch": "No LDAP/AD environment detected",
    "dig_any": "No DNS service; already have DNS records",
    "dig_axfr": "DNS server does not allow zone transfers (already tested)",
    "dnsrecon": "No DNS service; comprehensive DNS enumeration already done",
    "ssh_audit": "No SSH service detected (port 22 closed)",
    "snmpwalk": "No SNMP service detected (port 161 closed); no community string",
    "onesixtyone": "No SNMP service detected; community string already known",
    "showmount": "No NFS service (port 2049) detected",
    "rpcclient_null": "No RPC service; null sessions already tested and failed",
    "rpcclient_enumdomusers": "No RPC service; already have user list",
    "ftp_anonymous": "No FTP service; anonymous login already tested",
    "hydra_ssh": "No SSH service; or already have valid credentials",
    "hydra_ftp": "No FTP service; or already have valid credentials",
    "hydra_http_form": "No web login form identified",
    "cme_ldap_users": "No LDAP service; not an AD environment",
    "cme_smb_shares": "No SMB service; share enumeration already complete",
    "impacket_reg": "No admin credentials available; no remote registry access",
    "wpscan": "Target is not running WordPress",
    "nuclei_scan": "Stealth required — nuclei runs many templates and is noisy",
    "dirsearch": "Already have directory listing from gobuster/feroxbuster",
    "cme_smb_bruteforce": "No SMB service; account lockout policy in place",
    "sqlmap_test": "No SQL injection point identified; no web parameters to test",
    "searchsploit": "Already searched for exploits; or no version info available",
    "redis_cli": "No Redis service detected (port 6379 closed)",
    "certipy_find": "Not an AD environment; no ADCS detected",
    "enum4linux_scan": "No SMB/RPC; already ran enum4linux_full",
    "showmount_enum": "No NFS service (port 2049 closed)",
    "tomcat_cred_test": "No Tomcat service (port 8080/8180 closed)",
    "psql_default_creds": "No PostgreSQL service (port 5432 closed)",
    "joomscan": "Target is not running Joomla",
    "droopescan": "Target is not running Drupal",

    # EXPLOITATION
    "nfs_mount": "No NFS exports available; already mounted and explored",
    "hydra_smb": "No SMB service; or credentials already obtained",
    "crackmapexec_smb_bruteforce": "Account lockout policy active; no SMB service",
    "crackmapexec_winrm": "No WinRM service (5985/5986 closed); no credentials",
    "impacket_psexec": "No admin-level credentials; ADMIN$ share not accessible",
    "impacket_wmiexec": "No credentials; WMI not available (not Windows)",
    "impacket_smbexec": "No credentials; SMB not available",
    "impacket_GetNPUsers": "Not an AD environment; no usernames enumerated",
    "impacket_GetUserSPNs": "Not an AD environment; no valid credentials",
    "sqlmap_get": "No SQL injection point found in GET parameters",
    "sqlmap_post": "No SQL injection point found in POST parameters",
    "sqlmap_shell": "SQL injection not confirmed; DBMS does not support command execution",
    "evil_winrm": "No WinRM service; no credentials or hashes available",
    "evil_winrm_hash": "No WinRM service; no NTLM hashes available",
    "ssh_login": "No SSH service; no valid credentials",
    "ssh_key_login": "No SSH service; no private key available",
    "knock": "No port knocking sequence known",
    "nmap_port_knock": "No port knocking evidence; already triggered sequence",
    "cme_exec_command": "No admin-level credentials; no SMB access",
    "msfconsole_exploit": "No suitable Metasploit module identified; exploit already failed",
    "msfvenom_payload": "No delivery mechanism available; target architecture unknown",
    "impacket_atexec": "No credentials; task scheduler not accessible",
    "impacket_dcomexec": "No credentials; DCOM not available (not Windows)",
    "msfconsole_auto": "No specific exploit module identified for target services",
    "mysql_login": "No MySQL service; no credentials to try",
    "mssql_login": "No MSSQL service; no credentials to try",
    "rubeus_asreproast": "Not AD; no users with AS-REP pre-auth disabled",
    "rubeus_kerberoast": "Not AD; no SPN accounts found",
    "vsftpd_exploit": "vsftpd 2.3.4 not detected; port 21 not open",
    "unrealircd_exploit": "UnrealIRCd not detected; port 6667 not open",
    "telnet_1524": "Port 1524 not open; ingreslock backdoor not present",
    "root_shell_confirm": "No shell obtained yet",
    "rsh_root": "Port 514 not open; rsh not available",
    "rlogin_root": "Port 513 not open; rlogin not available",
    "war_deploy": "No Tomcat manager access; no admin credentials",
    "psql_rce": "No PostgreSQL access; not logged in as superuser",
    # --- Phase 18: Direct Exploit Scripts ---
    "vsftpd_backdoor_nc": "vsftpd 2.3.4 not detected; port 21 not open; already have root shell",
    "vsftpd_backdoor_python": "vsftpd 2.3.4 not detected; port 21 not open; already have root shell",
    "unrealircd_backdoor_nc": "UnrealIRCd not detected; port 6667 not open; already have root shell",
    "ingreslock_shell": "Port 1524 not open; already have root shell",
    "samba_usermap_exploit": "Samba 3.0.20 not detected; ports 139/445 not open; already have root shell",
    "tomcat_war_deploy": "Tomcat not on 8180; no default creds confirmed; already have shell",
    "mysql_noauth_root": "MySQL not on 3306; root password is set; already have DB access",
    "postgres_default_rce": "PostgreSQL not on 5432; default creds don't work; already have shell",
    "rlogin_noauth": "Port 513 not open; rlogin not available; already have root shell",
    "vnc_password_connect": "Port 5900 not open; VNC not needed if shell obtained",
    "nfs_mount_root": "NFS not on 2049; share not world-readable; already have file access",
    "python_reverse_shell": "No code execution available; no listener set up",
    "tty_stabilize": "No raw shell obtained; already have stable TTY",
    # --- Phase 19: HTB Soulmate / CrushFTP / Erlang / PCAP ---
    "crushftp_auth_bypass": "No CrushFTP service detected; port 80/443 not running CrushFTP; already have admin access",
    "crushftp_admin_reset_password": "CVE-2025-31161 not confirmed; admin user list not retrieved; already have admin creds",
    "crushftp_ftp_upload_shell": "No CrushFTP admin creds; FTP port not open; already have shell",
    "crushftp_ssh_as_user": "No CrushFTP creds available; SSH port 22 not open; already have shell",
    "erlang_cookie_extract": "No shell access; Erlang not running on target; already have cookie",
    "erlang_otp_rce": "No Erlang cookie; Erlang/OTP not running; already have root shell",
    "pcap_download_extract": "No PCAP files found on web server; already extracted credentials from PCAP",
    "tshark_pcap_creds": "No PCAP file downloaded; already extracted credentials; tshark not available",
    "vhost_discover": "No web server detected; already discovered all vhosts; no domain context",
    "ssti_detect_jinja2": "No template injection point; application does not use Jinja2",
    "ssti_exploit_jinja2": "Jinja2 SSTI not confirmed; detection step not done",
    "ssti_detect_twig": "No template injection point; application does not use Twig/PHP",
    "ssti_exploit_twig": "Twig SSTI not confirmed; detection step not done",
    "ssti_detect_erb": "No template injection point; application does not use ERB/Ruby",
    "tplmap_scan": "No template injection parameter identified",
    "lfi_etc_passwd": "No LFI parameter identified; application does not include files",
    "lfi_double_encode": "Standard LFI already worked; or no LFI parameter",
    "lfi_php_filter": "No LFI parameter; target is not PHP-based",
    "lfi_log_poison": "No LFI parameter; no writable log path found",
    "lfi_ssh_key": "No LFI parameter; SSH not available",
    "rfi_php_shell": "Target does not allow remote file inclusion; allow_url_include is off",
    "ssrf_localhost_scan": "No SSRF parameter identified",
    "ssrf_cloud_metadata": "Not a cloud instance; or SSRF not confirmed",
    "ssrf_internal_admin": "No SSRF parameter; no internal admin panels expected",
    "cmd_inject_semicolon": "No command injection point; input properly sanitized",
    "cmd_inject_pipe": "Semicolon injection already worked; no injection point",
    "cmd_inject_backtick": "Other injection methods already worked; no injection point",
    "cmd_inject_blind_sleep": "Command injection already confirmed with output",
    "shellshock_cgi": "No CGI scripts detected; target not vulnerable to Shellshock",
    "heartbleed_exploit": "OpenSSL not vulnerable (version >= 1.0.1g); no HTTPS",
    "log4shell_detect": "No Java application detected; Log4j not in use",
    "drupalgeddon2": "Target is not running Drupal 7.x/8.x",
    "upload_php_double_ext": "No file upload functionality; target not PHP-based",
    "upload_php_magic_bytes": "No file upload; simple extension bypass already worked",
    "upload_htaccess": "Not Apache; .htaccess not supported",
    "upload_aspx_shell": "Not IIS/ASP.NET; .aspx not supported",
    "webshell_cmd": "No webshell uploaded; no accessible web shell URL",
    "ysoserial_java": "No Java deserialization endpoint; not a Java application",
    "phpggc_laravel": "Not a Laravel/PHP application; no deserialization point",
    "jwt_none_attack": "Application does not use JWT; tokens not vulnerable",
    "jwt_crack_secret": "Application does not use JWT; or secret already known",
    "xxe_file_read": "No XML processing endpoint; XXE not applicable",
    "nosqli_login_bypass": "Not a MongoDB/NoSQL backend; or no login form",
    "revshell_bash": "Already have a shell; no code execution available",
    "revshell_python": "Already have a shell; Python not installed on target",
    "revshell_powershell": "Already have a shell; target is not Windows",
    "crackmapexec_password_spray": "Account lockout policy active; no username list",

    # PRIVILEGE ESCALATION
    "linpeas": "Already ran linpeas; already have root; target is Windows",
    "linpeas_local": "Already ran linpeas; already have root; target is Windows",
    "sudo_list": "Not a Linux target; already have root; no shell access",
    "find_suid": "Already have root; SUID check already done",
    "find_capabilities": "Already have root; not a Linux target",
    "find_writable_etc": "Already have root; /etc permissions already checked",
    "pspy": "Already have root; already identified cron jobs",
    "kernel_exploit_check": "Already have root; kernel version already known",
    "winpeas": "Target is not Windows; already have SYSTEM",
    "whoami_all": "Target is not Windows; already enumerated user privileges",
    "systeminfo": "Target is not Windows; already have system information",
    "windows_exploit_suggester": "Not Windows; already have SYSTEM",
    "accesschk_services": "Not Windows; already have SYSTEM; accesschk not uploaded",
    "powerup": "Not Windows; already have SYSTEM",
    "sudo_check": "Not Linux; already have root",
    "certipy_req": "Not AD; no vulnerable certificate template found",
    "find_sgid": "Already have root; not Linux",
    "cron_check": "Already have root; cron jobs already enumerated",
    "writable_etc_passwd": "Already have root; /etc/passwd not writable",
    "capability_check": "Already have root; capabilities already checked",
    "docker_privesc": "Not in docker group; docker not installed",
    "lxd_privesc": "Not in lxd group; lxd not installed",
    "pspy_monitor": "Already have root; process monitoring already done",
    "ssh_key_plant": "Already have root via other means; NFS not available",
    "docker_sock_escape": "Not inside a container; docker socket not accessible",
    "lxd_escape": "Not inside an LXD container",

    # LATERAL MOVEMENT
    "bloodhound_python": "Not AD; already have complete AD graph",
    "sharphound": "Not on a Windows domain host; not AD",
    "impacket_pth_psexec": "No NTLM hashes; SMB not available",
    "crackmapexec_pth": "No NTLM hashes; no additional targets",
    "responder": "Not on the same network segment; LLMNR/NBNS not in use",
    "ntlmrelayx": "SMB signing enforced; no relay targets available",
    "chisel_server": "Attacker server already set up; or direct access available",
    "chisel_client": "No chisel server running; direct network access available",
    "ligolo_agent": "No ligolo proxy running; direct access available",
    "ssh_tunnel_local": "No SSH access; direct network access to target",
    "ssh_tunnel_dynamic": "No SSH access; proxychains not needed",
    "pivot_scan": "No pivot host compromised; only one target in scope",
    "nmap_pivot": "No pivot host; direct network access",
    "proxychains_scan": "No SOCKS proxy established; direct access",
    "winrm_exec": "No WinRM access; no credentials for remote host",
    "ssh_lateral": "No SSH credentials for additional hosts",

    # EXFILTRATION
    "nc_exfil": "No data identified for exfiltration; no outbound network allowed",
    "curl_exfil": "No HTTP/S outbound allowed; no data to exfiltrate",
    "scp_exfil": "No SSH access from target to attacker; no data identified",
    "exfil_data": "No sensitive data located; exfiltration not in scope",
    "dns_exfil": "DNS not available for exfiltration; data too large for DNS tunneling",
    "icmp_exfil": "ICMP blocked by firewall; data too large",
    "base64_exfil": "Already have direct file transfer capability",
    "smb_exfil": "No SMB share available for exfiltration; not Windows",
    "exfil_shadow": "No root access; /etc/shadow not readable",
    "exfil_ssh_keys": "No SSH keys found on target",
    "exfil_mysql_dump": "No MySQL access; no database credentials",

    # POST EXPLOITATION
    "impacket_secretsdump": "No admin credentials; not Windows/AD",
    "secretsdump_dc": "Not a domain controller; no DA credentials",
    "mimikatz_logonpasswords": "Not Windows; already have all credentials",
    "mimikatz_sam": "Not Windows; SAM already dumped",
    "mimikatz_dcsync": "Not AD; not domain admin level",
    "cron_backdoor": "Not Linux; persistence not in scope; already have cron backdoor",
    "ssh_key_persistence": "Not Linux; already planted SSH key",
    "credential_dump": "No shell access; credentials already dumped",
    "hashdump": "Not Linux; /etc/shadow already exfiltrated",
    "keylogger_deploy": "Not in scope; no interactive user sessions",
    "history_dump": "No shell access; history already reviewed",
    "network_config_dump": "Network info already gathered",
    "ssh_key_harvest": "No shell access; SSH keys already collected",
    "cleanup_logs": "Engagement not complete; logs needed for evidence",
    "timestomp": "Anti-forensics not in scope",
    "dump_shadow": "Not Linux; no root access; already dumped",
    "dump_passwd": "Not Linux; already have /etc/passwd",
    "plant_ssh_key": "Not Linux; already have persistent access",

    # CLOSEOUT
    "remove_uploaded_tools": "No tools uploaded; engagement still active",
    "remove_ssh_keys_planted": "No SSH keys planted; engagement still active",
    "remove_cron_backdoors": "No cron backdoors created; engagement still active",
    "verify_target_stable": "Engagement still in progress; target health not a concern yet",
    "cleanup_tmp_artifacts": "No /tmp artifacts created; engagement still active",
    "clear_bash_history": "Evidence preservation required; engagement still active",
    "clear_auth_logs": "Evidence preservation required; not authorized",
    "clear_wtmp_btmp": "Evidence preservation required; engagement still active",
    "shred_sensitive_files": "No sensitive files to shred; engagement still active",
    "timestomp_closeout": "Anti-forensics not authorized in scope",
    "clear_syslog": "Evidence preservation required; engagement still active",
    "remove_known_hosts": "No known_hosts entries created; engagement still active",
    "generate_report": "Engagement still in progress; data collection incomplete",
}


# =============================================================================
# FOLLOWS_AFTER MAP — Typical predecessor commands
# =============================================================================

FOLLOWS_AFTER_MAP: Dict[str, List[str]] = {
    # RECON — mostly standalone but some have natural order
    "nmap_top_ports": ["nmap_quick_scan"],
    "nmap_full_tcp": ["nmap_top_ports"],
    "nmap_service_version": ["nmap_top_ports", "nmap_full_tcp"],
    "nmap_vuln_scan": ["nmap_service_version"],
    "nmap_udp_scan": ["nmap_top_ports"],
    "nmap_os_detection": ["nmap_service_version"],
    "whatweb": ["nmap_top_ports"],
    "curl_headers": ["nmap_top_ports"],
    "nmap_stealth_scan": ["nmap_quick_scan"],
    "nmap_comprehensive": ["nmap_quick_scan"],

    # ENUMERATION — follows recon
    "gobuster_dir": ["nmap_service_version", "whatweb"],
    "gobuster_vhost": ["whatweb", "gobuster_dir"],
    "ffuf_fuzz": ["gobuster_dir"],
    "nikto_scan": ["nmap_service_version"],
    "wfuzz_params": ["gobuster_dir"],
    "feroxbuster": ["nmap_service_version"],
    "smbclient_list": ["nmap_service_version", "enum4linux_full"],
    "smbclient_connect": ["smbclient_list", "smbmap_shares"],
    "smbclient_auth": ["hydra_smb", "cme_smb_bruteforce"],
    "smbmap_shares": ["nmap_service_version"],
    "enum4linux_full": ["nmap_service_version"],
    "enum4linux_ng": ["nmap_service_version"],
    "ldapsearch_base": ["nmap_service_version"],
    "ldapsearch_users": ["ldapsearch_base"],
    "windapsearch": ["ldapsearch_base"],
    "dig_any": ["nmap_service_version"],
    "dig_axfr": ["dig_any"],
    "dnsrecon": ["nmap_service_version"],
    "ssh_audit": ["nmap_service_version"],
    "snmpwalk": ["onesixtyone", "nmap_service_version"],
    "onesixtyone": ["nmap_udp_scan"],
    "showmount": ["rpcinfo_check", "nmap_service_version"],
    "rpcclient_null": ["nmap_service_version"],
    "rpcclient_enumdomusers": ["rpcclient_null"],
    "ftp_anonymous": ["nmap_service_version"],
    "hydra_ssh": ["nmap_service_version", "rpcclient_enumdomusers"],
    "hydra_ftp": ["nmap_service_version"],
    "hydra_http_form": ["gobuster_dir"],
    "cme_ldap_users": ["ldapsearch_base"],
    "cme_smb_shares": ["nmap_service_version"],
    "impacket_reg": ["impacket_psexec", "evil_winrm"],
    "wpscan": ["whatweb", "gobuster_dir"],
    "nuclei_scan": ["nmap_service_version"],
    "dirsearch": ["nmap_service_version"],
    "cme_smb_bruteforce": ["rpcclient_enumdomusers"],
    "sqlmap_test": ["gobuster_dir", "ffuf_fuzz"],
    "searchsploit": ["nmap_service_version"],
    "redis_cli": ["nmap_service_version"],
    "certipy_find": ["ldapsearch_base"],
    "enum4linux_scan": ["nmap_service_version"],
    "showmount_enum": ["rpcinfo_check"],
    "tomcat_cred_test": ["nmap_port_8180", "nmap_service_version"],
    "psql_default_creds": ["nmap_port_5432", "nmap_service_version"],
    "joomscan": ["whatweb"],
    "droopescan": ["whatweb"],

    # EXPLOITATION — follows enumeration
    "nfs_mount": ["showmount", "showmount_enum"],
    "hydra_smb": ["smbclient_list", "rpcclient_enumdomusers"],
    "crackmapexec_smb_bruteforce": ["rpcclient_enumdomusers"],
    "crackmapexec_winrm": ["hydra_ssh", "cme_smb_bruteforce"],
    "impacket_psexec": ["hydra_smb", "cme_smb_bruteforce", "impacket_secretsdump"],
    "impacket_wmiexec": ["hydra_smb", "cme_smb_bruteforce"],
    "impacket_smbexec": ["hydra_smb", "cme_smb_bruteforce"],
    "impacket_GetNPUsers": ["rpcclient_enumdomusers", "ldapsearch_users"],
    "impacket_GetUserSPNs": ["ldapsearch_users", "hydra_ssh"],
    "sqlmap_get": ["sqlmap_test", "gobuster_dir"],
    "sqlmap_post": ["sqlmap_test", "gobuster_dir"],
    "sqlmap_shell": ["sqlmap_get", "sqlmap_post"],
    "evil_winrm": ["hydra_ssh", "cme_smb_bruteforce"],
    "evil_winrm_hash": ["impacket_secretsdump", "mimikatz_logonpasswords"],
    "ssh_login": ["hydra_ssh"],
    "ssh_key_login": ["lfi_ssh_key", "ssh_key_harvest"],
    "cme_exec_command": ["cme_smb_bruteforce", "hydra_smb"],
    "msfconsole_exploit": ["searchsploit", "nmap_vuln_scan"],
    "msfvenom_payload": ["nmap_service_version", "nmap_os_detection"],
    "impacket_atexec": ["hydra_smb", "cme_smb_bruteforce"],
    "impacket_dcomexec": ["hydra_smb", "cme_smb_bruteforce"],
    "msfconsole_auto": ["searchsploit", "nmap_vuln_scan"],
    "mysql_login": ["nmap_service_version"],
    "mssql_login": ["nmap_service_version"],
    "rubeus_asreproast": ["ldapsearch_users", "bloodhound_python"],
    "rubeus_kerberoast": ["ldapsearch_users", "bloodhound_python"],
    "vsftpd_exploit": ["nmap_port_21", "nmap_service_version"],
    "unrealircd_exploit": ["nmap_port_6667", "nmap_service_version"],
    "telnet_1524": ["nmap_port_1524"],
    "root_shell_confirm": ["vsftpd_exploit", "unrealircd_exploit", "telnet_1524", "rsh_root",
                           "vsftpd_backdoor_nc", "vsftpd_backdoor_python", "unrealircd_backdoor_nc",
                           "ingreslock_shell", "samba_usermap_exploit", "rlogin_noauth"],
    "rsh_root": ["nmap_rservices"],
    "rlogin_root": ["nmap_rservices"],
    "war_deploy": ["tomcat_cred_test"],
    "psql_rce": ["psql_default_creds"],
    # --- Phase 18: Direct Exploit Scripts ---
    "vsftpd_backdoor_nc": ["nmap_port_21", "nmap_service_version", "ftp_enum"],
    "vsftpd_backdoor_python": ["nmap_port_21", "nmap_service_version", "ftp_enum"],
    "unrealircd_backdoor_nc": ["nmap_port_6667", "nmap_service_version"],
    "ingreslock_shell": ["nmap_full_tcp", "nmap_port_1524"],
    "samba_usermap_exploit": ["smb_enum", "nmap_service_version"],
    "tomcat_war_deploy": ["http_enum", "nmap_service_version", "tomcat_cred_test"],
    "mysql_noauth_root": ["nmap_service_version"],
    "postgres_default_rce": ["nmap_service_version", "psql_default_creds"],
    "rlogin_noauth": ["nmap_full_tcp", "nmap_rservices"],
    "vnc_password_connect": ["nmap_full_tcp"],
    "nfs_mount_root": ["showmount", "showmount_enum", "nmap_service_version"],
    "python_reverse_shell": ["vsftpd_backdoor_nc", "unrealircd_backdoor_nc", "ingreslock_shell"],
    "tty_stabilize": ["python_reverse_shell", "vsftpd_backdoor_nc", "ingreslock_shell"],
    # --- Phase 19: HTB Soulmate / CrushFTP / Erlang / PCAP ---
    "crushftp_auth_bypass": ["nmap_service_version", "vhost_discover", "whatweb"],
    "crushftp_admin_reset_password": ["crushftp_auth_bypass"],
    "crushftp_ftp_upload_shell": ["crushftp_admin_reset_password"],
    "crushftp_ssh_as_user": ["crushftp_admin_reset_password"],
    "erlang_cookie_extract": ["crushftp_ssh_as_user", "ssh_login"],
    "erlang_otp_rce": ["erlang_cookie_extract"],
    "pcap_download_extract": ["gobuster_dir", "nmap_service_version"],
    "tshark_pcap_creds": ["pcap_download_extract"],
    "vhost_discover": ["nmap_service_version", "whatweb"],
    "ssti_detect_jinja2": ["gobuster_dir", "ffuf_fuzz"],
    "ssti_exploit_jinja2": ["ssti_detect_jinja2"],
    "ssti_detect_twig": ["gobuster_dir", "whatweb"],
    "ssti_exploit_twig": ["ssti_detect_twig"],
    "ssti_detect_erb": ["gobuster_dir", "whatweb"],
    "tplmap_scan": ["gobuster_dir", "ffuf_fuzz"],
    "lfi_etc_passwd": ["gobuster_dir", "ffuf_fuzz"],
    "lfi_double_encode": ["lfi_etc_passwd"],
    "lfi_php_filter": ["lfi_etc_passwd"],
    "lfi_log_poison": ["lfi_etc_passwd"],
    "lfi_ssh_key": ["lfi_etc_passwd"],
    "rfi_php_shell": ["lfi_etc_passwd", "gobuster_dir"],
    "ssrf_localhost_scan": ["gobuster_dir", "ffuf_fuzz"],
    "ssrf_cloud_metadata": ["ssrf_localhost_scan"],
    "ssrf_internal_admin": ["ssrf_localhost_scan"],
    "cmd_inject_semicolon": ["gobuster_dir", "ffuf_fuzz"],
    "cmd_inject_pipe": ["cmd_inject_semicolon"],
    "cmd_inject_backtick": ["cmd_inject_semicolon"],
    "cmd_inject_blind_sleep": ["cmd_inject_semicolon"],
    "shellshock_cgi": ["nikto_scan", "gobuster_dir"],
    "heartbleed_exploit": ["nmap_service_version"],
    "log4shell_detect": ["nmap_service_version", "whatweb"],
    "drupalgeddon2": ["droopescan", "whatweb"],
    "upload_php_double_ext": ["gobuster_dir"],
    "upload_php_magic_bytes": ["upload_php_double_ext"],
    "upload_htaccess": ["upload_php_double_ext"],
    "upload_aspx_shell": ["gobuster_dir"],
    "webshell_cmd": ["upload_php_double_ext", "upload_htaccess", "upload_aspx_shell"],
    "ysoserial_java": ["nmap_service_version"],
    "phpggc_laravel": ["whatweb", "gobuster_dir"],
    "jwt_none_attack": ["gobuster_dir"],
    "jwt_crack_secret": ["jwt_none_attack"],
    "xxe_file_read": ["gobuster_dir", "ffuf_fuzz"],
    "nosqli_login_bypass": ["gobuster_dir"],
    "revshell_bash": ["cmd_inject_semicolon", "lfi_log_poison", "ssti_exploit_jinja2"],
    "revshell_python": ["cmd_inject_semicolon", "ssti_exploit_jinja2"],
    "revshell_powershell": ["cmd_inject_semicolon"],
    "crackmapexec_password_spray": ["ldapsearch_users", "rpcclient_enumdomusers"],

    # PRIVILEGE ESCALATION — follows initial access
    "linpeas": ["ssh_login", "revshell_bash", "vsftpd_exploit"],
    "linpeas_local": ["ssh_login", "revshell_bash"],
    "sudo_list": ["ssh_login", "revshell_bash"],
    "find_suid": ["ssh_login", "revshell_bash"],
    "find_capabilities": ["ssh_login", "revshell_bash"],
    "find_writable_etc": ["ssh_login", "revshell_bash"],
    "pspy": ["ssh_login", "revshell_bash"],
    "kernel_exploit_check": ["ssh_login", "systeminfo"],
    "winpeas": ["evil_winrm", "impacket_psexec"],
    "whoami_all": ["evil_winrm", "impacket_psexec"],
    "systeminfo": ["evil_winrm", "impacket_psexec"],
    "windows_exploit_suggester": ["systeminfo"],
    "accesschk_services": ["evil_winrm", "impacket_psexec"],
    "powerup": ["evil_winrm", "impacket_psexec"],
    "sudo_check": ["ssh_login", "revshell_bash"],
    "certipy_req": ["certipy_find"],
    "find_sgid": ["ssh_login", "revshell_bash"],
    "cron_check": ["ssh_login", "revshell_bash"],
    "writable_etc_passwd": ["find_writable_etc"],
    "capability_check": ["ssh_login", "revshell_bash"],
    "docker_privesc": ["linpeas", "ssh_login"],
    "lxd_privesc": ["linpeas", "ssh_login"],
    "pspy_monitor": ["ssh_login", "revshell_bash"],
    "ssh_key_plant": ["nfs_mount"],
    "docker_sock_escape": ["linpeas", "ssh_login"],
    "lxd_escape": ["linpeas", "ssh_login"],

    # LATERAL MOVEMENT
    "bloodhound_python": ["ldapsearch_users", "impacket_GetUserSPNs"],
    "sharphound": ["evil_winrm", "impacket_psexec"],
    "impacket_pth_psexec": ["impacket_secretsdump", "mimikatz_logonpasswords"],
    "crackmapexec_pth": ["impacket_secretsdump", "mimikatz_logonpasswords"],
    "responder": ["nmap_quick_scan"],
    "ntlmrelayx": ["responder"],
    "chisel_server": ["ssh_login", "revshell_bash"],
    "chisel_client": ["chisel_server"],
    "ligolo_agent": ["ssh_login", "revshell_bash"],
    "ssh_tunnel_local": ["ssh_login"],
    "ssh_tunnel_dynamic": ["ssh_login"],
    "pivot_scan": ["chisel_client", "ssh_tunnel_dynamic"],
    "nmap_pivot": ["pivot_scan", "chisel_client"],
    "proxychains_scan": ["ssh_tunnel_dynamic", "chisel_client"],
    "winrm_exec": ["crackmapexec_pth", "impacket_pth_psexec"],
    "ssh_lateral": ["ssh_key_harvest", "credential_dump"],

    # EXFILTRATION
    "nc_exfil": ["credential_dump", "dump_shadow"],
    "curl_exfil": ["credential_dump"],
    "scp_exfil": ["ssh_login", "credential_dump"],
    "exfil_data": ["credential_dump"],
    "dns_exfil": ["credential_dump"],
    "icmp_exfil": ["credential_dump"],
    "base64_exfil": ["credential_dump"],
    "smb_exfil": ["credential_dump"],
    "exfil_shadow": ["dump_shadow"],
    "exfil_ssh_keys": ["ssh_key_harvest"],
    "exfil_mysql_dump": ["mysql_login"],

    # POST EXPLOITATION
    "impacket_secretsdump": ["impacket_psexec", "evil_winrm"],
    "secretsdump_dc": ["impacket_psexec", "mimikatz_dcsync"],
    "mimikatz_logonpasswords": ["evil_winrm", "impacket_psexec"],
    "mimikatz_sam": ["evil_winrm", "impacket_psexec"],
    "mimikatz_dcsync": ["bloodhound_python", "impacket_psexec"],
    "cron_backdoor": ["ssh_login", "revshell_bash"],
    "ssh_key_persistence": ["ssh_login", "revshell_bash"],
    "credential_dump": ["ssh_login", "revshell_bash", "evil_winrm"],
    "hashdump": ["ssh_login", "revshell_bash"],
    "keylogger_deploy": ["ssh_login", "evil_winrm"],
    "history_dump": ["ssh_login", "revshell_bash"],
    "network_config_dump": ["ssh_login", "revshell_bash"],
    "ssh_key_harvest": ["ssh_login", "revshell_bash"],
    "cleanup_logs": ["credential_dump", "exfil_data"],
    "timestomp": ["cron_backdoor", "ssh_key_persistence"],
    "dump_shadow": ["ssh_login", "root_shell_confirm"],
    "dump_passwd": ["ssh_login", "revshell_bash"],
    "plant_ssh_key": ["ssh_login", "root_shell_confirm"],

    # CLOSEOUT
    "remove_uploaded_tools": ["exfil_data", "credential_dump"],
    "remove_ssh_keys_planted": ["ssh_key_persistence", "plant_ssh_key"],
    "remove_cron_backdoors": ["cron_backdoor"],
    "verify_target_stable": ["remove_uploaded_tools", "remove_cron_backdoors"],
    "cleanup_tmp_artifacts": ["exfil_data"],
    "clear_bash_history": ["cleanup_logs"],
    "clear_auth_logs": ["cleanup_logs"],
    "clear_wtmp_btmp": ["cleanup_logs"],
    "shred_sensitive_files": ["cleanup_logs"],
    "timestomp_closeout": ["cleanup_logs"],
    "clear_syslog": ["cleanup_logs"],
    "remove_known_hosts": ["ssh_lateral"],
    "generate_report": ["verify_target_stable", "remove_uploaded_tools"],
}


# =============================================================================
# ENABLES MAP — What each command unlocks
# =============================================================================

ENABLES_MAP: Dict[str, List[str]] = {
    # RECON
    "nmap_quick_scan": ["nmap_top_ports", "nmap_full_tcp"],
    "nmap_top_ports": ["nmap_service_version", "gobuster_dir", "nikto_scan"],
    "nmap_full_tcp": ["nmap_service_version"],
    "nmap_service_version": ["searchsploit", "msfconsole_exploit", "hydra_ssh", "enum4linux_full"],
    "nmap_vuln_scan": ["msfconsole_exploit", "msfconsole_auto"],
    "nmap_udp_scan": ["onesixtyone", "snmpwalk"],
    "masscan_fast": ["nmap_service_version"],
    "nmap_os_detection": ["kernel_exploit_check", "msfvenom_payload"],
    "whatweb": ["wpscan", "joomscan", "droopescan"],
    "curl_headers": ["gobuster_dir"],
    "nmap_stealth_scan": ["nmap_service_version"],
    "nmap_comprehensive": ["searchsploit", "msfconsole_exploit"],
    "dns_enum": ["dig_axfr", "dnsrecon"],
    "nmap_port_21": ["ftp_anonymous", "vsftpd_exploit"],
    "nmap_port_6667": ["unrealircd_exploit"],
    "nmap_port_1524": ["telnet_1524"],
    "nmap_port_8180": ["tomcat_cred_test"],
    "nmap_port_5432": ["psql_default_creds"],
    "nmap_rservices": ["rsh_root", "rlogin_root"],
    "rpcinfo_check": ["showmount", "showmount_enum"],

    # ENUMERATION
    "gobuster_dir": ["ffuf_fuzz", "sqlmap_test", "lfi_etc_passwd", "ssti_detect_jinja2"],
    "gobuster_vhost": ["gobuster_dir"],
    "ffuf_fuzz": ["sqlmap_test", "cmd_inject_semicolon", "ssti_detect_jinja2"],
    "nikto_scan": ["shellshock_cgi", "gobuster_dir"],
    "smbclient_list": ["smbclient_connect"],
    "smbclient_connect": ["smbclient_auth"],
    "smbmap_shares": ["smbclient_connect"],
    "enum4linux_full": ["rpcclient_enumdomusers", "hydra_smb"],
    "ldapsearch_base": ["ldapsearch_users", "cme_ldap_users"],
    "ldapsearch_users": ["impacket_GetNPUsers", "impacket_GetUserSPNs", "crackmapexec_password_spray"],
    "rpcclient_null": ["rpcclient_enumdomusers"],
    "rpcclient_enumdomusers": ["hydra_smb", "cme_smb_bruteforce", "crackmapexec_password_spray"],
    "ftp_anonymous": ["exfil_data"],
    "hydra_ssh": ["ssh_login"],
    "hydra_ftp": ["ftp_anonymous"],
    "hydra_http_form": ["gobuster_dir"],
    "cme_smb_bruteforce": ["impacket_psexec", "impacket_wmiexec", "cme_exec_command"],
    "sqlmap_test": ["sqlmap_get", "sqlmap_post"],
    "searchsploit": ["msfconsole_exploit", "msfconsole_auto"],
    "certipy_find": ["certipy_req"],
    "showmount_enum": ["nfs_mount"],
    "tomcat_cred_test": ["war_deploy"],
    "psql_default_creds": ["psql_rce"],
    "onesixtyone": ["snmpwalk"],
    "showmount": ["nfs_mount"],

    # EXPLOITATION
    "nfs_mount": ["ssh_key_plant"],
    "hydra_smb": ["impacket_psexec", "impacket_wmiexec", "impacket_smbexec"],
    "crackmapexec_smb_bruteforce": ["impacket_psexec", "cme_exec_command"],
    "impacket_psexec": ["impacket_secretsdump", "mimikatz_logonpasswords", "credential_dump"],
    "impacket_wmiexec": ["credential_dump", "impacket_secretsdump"],
    "impacket_GetNPUsers": ["hashcat", "john"],
    "impacket_GetUserSPNs": ["hashcat", "john"],
    "sqlmap_get": ["sqlmap_shell"],
    "sqlmap_post": ["sqlmap_shell"],
    "sqlmap_shell": ["credential_dump"],
    "evil_winrm": ["impacket_secretsdump", "mimikatz_logonpasswords", "winpeas"],
    "evil_winrm_hash": ["impacket_secretsdump", "mimikatz_logonpasswords"],
    "ssh_login": ["linpeas", "sudo_list", "find_suid", "credential_dump"],
    "ssh_key_login": ["linpeas", "sudo_list"],
    "msfconsole_exploit": ["credential_dump", "root_shell_confirm"],
    "vsftpd_exploit": ["root_shell_confirm", "dump_shadow", "dump_passwd"],
    "unrealircd_exploit": ["root_shell_confirm", "dump_shadow"],
    "telnet_1524": ["root_shell_confirm", "dump_shadow"],
    "root_shell_confirm": ["dump_shadow", "dump_passwd", "plant_ssh_key"],
    "rsh_root": ["root_shell_confirm", "dump_shadow"],
    "rlogin_root": ["root_shell_confirm", "dump_shadow"],
    "war_deploy": ["webshell_cmd"],
    "psql_rce": ["credential_dump"],
    # --- Phase 18: Direct Exploit Scripts ---
    "vsftpd_backdoor_nc": ["root_shell_confirm", "dump_shadow", "dump_passwd", "tty_stabilize"],
    "vsftpd_backdoor_python": ["root_shell_confirm", "dump_shadow", "dump_passwd"],
    "unrealircd_backdoor_nc": ["root_shell_confirm", "dump_shadow", "dump_passwd"],
    "ingreslock_shell": ["root_shell_confirm", "dump_shadow", "dump_passwd", "tty_stabilize"],
    "samba_usermap_exploit": ["root_shell_confirm", "dump_shadow"],
    "tomcat_war_deploy": ["webshell_cmd", "credential_dump"],
    "mysql_noauth_root": ["credential_dump", "dump_shadow"],
    "postgres_default_rce": ["credential_dump", "dump_shadow"],
    "rlogin_noauth": ["root_shell_confirm", "dump_shadow"],
    "vnc_password_connect": ["credential_dump"],
    "nfs_mount_root": ["credential_dump", "dump_shadow", "dump_passwd", "plant_ssh_key"],
    "python_reverse_shell": ["tty_stabilize", "linpeas", "sudo_list"],
    "tty_stabilize": ["linpeas", "sudo_list", "find_suid"],
    # --- Phase 19: HTB Soulmate / CrushFTP / Erlang / PCAP ---
    "crushftp_auth_bypass": ["crushftp_admin_reset_password"],
    "crushftp_admin_reset_password": ["crushftp_ftp_upload_shell", "crushftp_ssh_as_user"],
    "crushftp_ftp_upload_shell": ["webshell_cmd"],
    "crushftp_ssh_as_user": ["erlang_cookie_extract", "linpeas", "sudo_list", "find_suid"],
    "erlang_cookie_extract": ["erlang_otp_rce"],
    "erlang_otp_rce": ["root_shell_confirm", "dump_shadow", "dump_passwd"],
    "pcap_download_extract": ["tshark_pcap_creds", "ssh_login"],
    "tshark_pcap_creds": ["ssh_login", "hydra_ssh"],
    "vhost_discover": ["gobuster_dir", "crushftp_auth_bypass", "ffuf_fuzz"],
    "ssti_detect_jinja2": ["ssti_exploit_jinja2"],
    "ssti_exploit_jinja2": ["revshell_bash", "revshell_python"],
    "ssti_detect_twig": ["ssti_exploit_twig"],
    "lfi_etc_passwd": ["lfi_double_encode", "lfi_php_filter", "lfi_log_poison", "lfi_ssh_key"],
    "lfi_log_poison": ["revshell_bash"],
    "lfi_ssh_key": ["ssh_key_login"],
    "ssrf_localhost_scan": ["ssrf_cloud_metadata", "ssrf_internal_admin"],
    "cmd_inject_semicolon": ["revshell_bash", "revshell_python"],
    "upload_htaccess": ["webshell_cmd"],
    "upload_php_double_ext": ["webshell_cmd"],
    "upload_aspx_shell": ["webshell_cmd"],
    "webshell_cmd": ["revshell_bash", "credential_dump"],
    "revshell_bash": ["linpeas", "sudo_list", "find_suid"],
    "revshell_python": ["linpeas", "sudo_list"],

    # PRIVILEGE ESCALATION
    "linpeas": ["find_suid", "docker_privesc", "lxd_privesc", "cron_check"],
    "sudo_list": ["sudo_check"],
    "find_suid": ["kernel_exploit_check"],
    "find_writable_etc": ["writable_etc_passwd"],
    "pspy": ["cron_backdoor"],
    "kernel_exploit_check": ["msfconsole_exploit"],
    "winpeas": ["accesschk_services", "powerup"],
    "systeminfo": ["windows_exploit_suggester"],
    "ssh_key_plant": ["ssh_key_login"],

    # LATERAL MOVEMENT
    "bloodhound_python": ["impacket_pth_psexec", "rubeus_kerberoast"],
    "sharphound": ["bloodhound_python"],
    "impacket_pth_psexec": ["impacket_secretsdump"],
    "responder": ["ntlmrelayx"],
    "chisel_server": ["chisel_client"],
    "chisel_client": ["pivot_scan", "nmap_pivot", "proxychains_scan"],
    "ssh_tunnel_local": ["pivot_scan"],
    "ssh_tunnel_dynamic": ["proxychains_scan"],

    # EXFILTRATION
    "exfil_shadow": ["hashcat", "john"],

    # POST EXPLOITATION
    "impacket_secretsdump": ["impacket_pth_psexec", "crackmapexec_pth", "evil_winrm_hash"],
    "mimikatz_logonpasswords": ["impacket_pth_psexec", "crackmapexec_pth"],
    "mimikatz_dcsync": ["impacket_pth_psexec", "secretsdump_dc"],
    "credential_dump": ["ssh_lateral", "nc_exfil", "exfil_data"],
    "ssh_key_harvest": ["ssh_lateral", "ssh_key_login"],

    # CLOSEOUT
    "remove_uploaded_tools": ["verify_target_stable"],
    "remove_cron_backdoors": ["verify_target_stable"],
    "verify_target_stable": ["generate_report"],
}


def enrich_registry(registry: Dict) -> int:
    """
    Enrich all commands in the registry with assigned_agents, not_when,
    follows_after, and enables metadata.
    
    Args:
        registry: The COMMAND_REGISTRY dict to enrich.
        
    Returns:
        Number of commands enriched.
    """
    enriched = 0

    for name, cmd in registry.items():
        changed = False

        # Assign agents
        if not cmd.assigned_agents and name in AGENT_MAP:
            cmd.assigned_agents = AGENT_MAP[name]
            changed = True

        # Add not_when
        if not cmd.not_when and name in NOT_WHEN_MAP:
            cmd.not_when = NOT_WHEN_MAP[name]
            changed = True

        # Add follows_after
        if not cmd.follows_after and name in FOLLOWS_AFTER_MAP:
            cmd.follows_after = FOLLOWS_AFTER_MAP[name]
            changed = True

        # Add enables
        if not cmd.enables and name in ENABLES_MAP:
            cmd.enables = ENABLES_MAP[name]
            changed = True

        # Infer agents from phase+tags if not explicitly mapped
        if not cmd.assigned_agents:
            cmd.assigned_agents = _infer_agents(cmd)
            changed = True

        if changed:
            enriched += 1

    return enriched


def _infer_agents(cmd) -> List[str]:
    """Infer agent assignment from phase and tags when not explicitly mapped."""
    from core.commands.command_registry import AttackPhase

    tags = cmd.tags if cmd.tags else set()
    phase = cmd.phase

    # Phase-based defaults
    if phase == AttackPhase.RECON:
        return ["scout"]
    elif phase == AttackPhase.ENUMERATION:
        if tags & {"bruteforce", "credentials", "sqli"}:
            return ["red"]
        return ["scout"]
    elif phase in (AttackPhase.EXPLOITATION, AttackPhase.PRIVILEGE_ESCALATION):
        return ["red"]
    elif phase == AttackPhase.LATERAL_MOVEMENT:
        if tags & {"pivot", "scan", "nmap"}:
            return ["scout"]
        return ["red"]
    elif phase == AttackPhase.EXFILTRATION:
        if tags & {"stealth", "dns", "icmp"}:
            return ["red", "shadow"]
        return ["red"]
    elif phase == AttackPhase.POST_EXPLOITATION:
        if tags & {"cleanup", "antiforensics"}:
            return ["red", "shadow"]
        return ["red"]
    elif phase == AttackPhase.CLOSEOUT:
        if tags & {"report", "verify"}:
            return ["orion", "blue"]
        if tags & {"anti-forensics"}:
            return ["red", "shadow"]
        return ["red", "blue"]

    return ["red"]
